[versions]
agp = "8.3.2"
auth = "2.1.1"
dotenvJava = "3.0.0"
firebaseBom = "32.8.1"
firebaseUiAuth = "8.0.2"
googleServices = "4.4.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.11.0"
constraintlayout = "2.1.4"
lifecycleLivedataKtx = "2.7.0"
lifecycleViewmodelKtx = "2.7.0"
navigationFragment = "2.7.7"
navigationUi = "2.7.7"
okhttp = "4.12.0"
picasso = "2.8"
annotation = "1.7.1"
legacySupportV4 = "1.0.0"
recyclerview = "1.3.2"

[libraries]
auth = { module = "com.spotify.android:auth", version.ref = "auth" }
dotenv-java = { module = "io.github.cdimascio:dotenv-java", version.ref = "dotenvJava" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { module = 'com.google.firebase:firebase-analytics'}
firebase-ui-auth = { module = "com.firebaseui:firebase-ui-auth", version.ref = "firebaseUiAuth" }
firebase-auth = { module = "com.google.firebase:firebase-auth"}
firebase-database = { module = "com.google.firebase:firebase-database"}
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupportV4" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
googleServices = {id = "com.google.gms.google-services", version.ref = "googleServices"}
